# Code coverage

name: code-coverage

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  code_coverage:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install dependencies
        run: |
            sudo apt-get update
            sudo apt-get install lcov libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev mesa-common-dev libgl1-mesa-dev -qyy
      - name: prepare
        run: mkdir -p build
      - name: configure
        run: cmake .. -DCMAKE_BUILD_TYPE=Release -DHG_ENABLE_COVERAGE:BOOl=ON
        working-directory: build
      - name: build
        run: cmake --build . --target foundation_coverage
        working-directory: build
      - name: results
        shell: bash
        run: |
          echo "::group::Report code coverage"
          lcov --list foundation_coverage.info
          echo "::endgroup::"
        working-directory: build
      - name: upload results
        uses: actions/upload-artifact@v3
        with:
          name: coverage-results
          path: build/foundation_coverage
